[package]
name = "ray-tracer"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
async-trait = "0.1"
cucumber = { version = "0.11", features = ["output-junit"] }
futures = "0.3"
rayon = "1.5"

[[test]]
name = "tuples"
harness = false
